"""empty message

Revision ID: 0a0056204b92
Revises: ce5ec755852b
Create Date: 2022-03-24 16:54:31.361818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0056204b92'
down_revision = 'ce5ec755852b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_details', sa.Column('contactdetails', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_details', 'contactdetails')
    # ### end Alembic commands ###
