"""empty message

Revision ID: 31c19a8d4a45
Revises: 0a0056204b92
Create Date: 2022-03-25 11:12:21.427268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c19a8d4a45'
down_revision = '0a0056204b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_employee_details_empid', table_name='employee_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_employee_details_empid', 'employee_details', ['empid'], unique=False)
    # ### end Alembic commands ###
