"""empty message

Revision ID: 66aa44d43f11
Revises: 
Create Date: 2022-03-26 18:19:00.457320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66aa44d43f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_details',
    sa.Column('empid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('personaladdress', sa.String(length=200), nullable=False),
    sa.Column('contactdetails', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('empid')
    )
    op.create_table('service_locations',
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('serviceaddress', sa.String(length=500), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['employee_details.empid'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_locations')
    op.drop_table('employee_details')
    # ### end Alembic commands ###
